//
// BatchRequestResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class BatchRequestResult: JSONEncodable {
    /** HTTP response code for the processed request */
    public var code: Int32?
    /** Error messages if the request could not be processed */
    public var errors: [String]?
    /** The request. Will be null if request was successfully processed */
    public var request: DataCollectorBaseRequest?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["code"] = self.code?.encodeToJSON()
        nillableDictionary["errors"] = self.errors?.encodeToJSON()
        nillableDictionary["request"] = self.request?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
