//
// EventsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class EventsAPI: APIBase {
    /**
     Creates a single event (a transaction with no duration)
     
     - parameter customerId: (query) customerId 
     - parameter request: (body) Similar to transactions, the details of that event (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func createEventUsingPOST(customerId customerId: String, request: NewEventRequest? = nil, completion: ((error: ErrorType?) -> Void)) {
        createEventUsingPOSTWithRequestBuilder(customerId: customerId, request: request).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Creates a single event (a transaction with no duration)
     - POST /v2/events
     
     - parameter customerId: (query) customerId 
     - parameter request: (body) Similar to transactions, the details of that event (optional)

     - returns: RequestBuilder<Void> 
     */
    public class func createEventUsingPOSTWithRequestBuilder(customerId customerId: String, request: NewEventRequest? = nil) -> RequestBuilder<Void> {
        let path = "/v2/events"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = request?.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

}
